services:
  - type: web
    name: hrnet
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_BASE_URL
        fromFile: .env.production
    staticPublishPath: build

  - type: web
    name: json-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
